language: swift
osx_image: xcode11.2

xcode_workspace: NinchatSDKSwift.xcworkspace
xcode_scheme: NinchatSDKSwift
xcode_destination: platform=iOS Simulator,name=iPhone 8

before_install:
  - brew install cocoapods
  - pod setup

  - gem install ocunit2junit
  - gem install xcpretty

  - pod update
  - pod install

script:
  - set -o pipefail && xcodebuild clean
  - set -o pipefail && xcodebuild -workspace NinchatSDKSwift.xcworkspace -scheme NinchatSDKSwift -configuration "Release" -destination "platform=iOS Simulator,name=iPhone 8" | tee raw.txt | xcpretty -c cat raw.txt | ocunit2junit
  - set -o pipefail && xcodebuild test -workspace NinchatSDKSwift.xcworkspace -scheme NinchatSDKSwift -destination "platform=iOS Simulator,name=iPhone 8" | tee rawTest.txt | xcpretty -c cat rawTest.txt | ocunit2junit
