
// Objective-C API for talking to the following Go packages
//
//	github.com/ninchat/ninchat-go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NinchatLowLevelClient_FRAMEWORK_H__
#define __NinchatLowLevelClient_FRAMEWORK_H__

#include "NINLowLevelClient.objc.h"
#include "Universe.objc.h"

#endif
