
// Objective-C API for talking to the following Go packages
//
//	github.com/ninchat/ninchat-go/mobile
//
// File is generated by gomobile bind. Do not edit.

#import "ref.h"
#import "Universe.objc.h"
#import "NINLowLevelClient.objc.h"

