name: Ninchat SwiftSDK

on:
    push:
        branches:
            - '*'
            - '*/*'

jobs:
    build_test_SDK:
        runs-on: macos-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Shell Environment
              run: export SHELL=/bin/bash

            - name: Force Xcode 12
              run: sudo xcode-select -switch /Applications/Xcode_12.4.app

            - name: Install Cocoapods
              run: pod update

            - name: Build SDK. Run Tests
              run: xcodebuild test -workspace NinchatSDKSwift.xcworkspace -scheme NinchatSDKSwift -destination "platform=iOS Simulator,name=iPhone 11" "OTHER_LDFLAGS=\$(OTHER_LDFLAGS) -read_only_relocs suppress" ONLY_ACTIVE_ARCH=YES
